service: lambda-fetch-external-contacts

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: false

functions:
  fetchExternalContacts:
    handler: src/index.handler
